// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) annotate safe 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.*;
import com.google.android.gms.common.internal.zzac;
import java.util.concurrent.TimeUnit;

public class zzabh extends PendingResult
{

	public zzabh(Status status)
	{
	//    0    0:aload_0         
	//    1    1:invokespecial   #12  <Method void PendingResult()>
		zzac.zzb(((Object) (status)), "Status must not be null");
	//    2    4:aload_1         
	//    3    5:ldc1            #14  <String "Status must not be null">
	//    4    7:invokestatic    #20  <Method Object zzac.zzb(Object, Object)>
	//    5   10:pop             
		boolean flag;
		if(!status.isSuccess())
	//*   6   11:aload_1         
	//*   7   12:invokevirtual   #26  <Method boolean Status.isSuccess()>
	//*   8   15:ifne            32
			flag = true;
	//    9   18:iconst_1        
	//   10   19:istore_2        
		else
	//*  11   20:iload_2         
	//*  12   21:ldc1            #28  <String "Status must not be success">
	//*  13   23:invokestatic    #31  <Method void zzac.zzb(boolean, Object)>
	//*  14   26:aload_0         
	//*  15   27:aload_1         
	//*  16   28:putfield        #33  <Field Status zzahq>
	//*  17   31:return          
			flag = false;
	//   18   32:iconst_0        
	//   19   33:istore_2        
		zzac.zzb(flag, "Status must not be success");
		zzahq = status;
	//*  20   34:goto            20
	}

	public Result await()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public Result await(long l, TimeUnit timeunit)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void cancel()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	Status getStatus()
	{
		return zzahq;
	//    0    0:aload_0         
	//    1    1:getfield        #33  <Field Status zzahq>
	//    2    4:areturn         
	}

	public boolean isCanceled()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void setResultCallback(ResultCallback resultcallback)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void setResultCallback(ResultCallback resultcallback, long l, TimeUnit timeunit)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public TransformedResult then(ResultTransform resulttransform)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void zza(com.google.android.gms.common.api.PendingResult.zza zza1)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public Integer zzuR()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	private final Status zzahq;
}
