// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) annotate safe 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.*;
import java.util.concurrent.TimeUnit;

// Referenced classes of package com.google.android.gms.internal:
//			zzaaf

public final class zzabk extends OptionalPendingResult
{

	public zzabk(PendingResult pendingresult)
	{
	//    0    0:aload_0         
	//    1    1:invokespecial   #13  <Method void OptionalPendingResult()>
		if(!(pendingresult instanceof zzaaf))
	//*   2    4:aload_1         
	//*   3    5:instanceof      #15  <Class zzaaf>
	//*   4    8:ifne            21
		{
			throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
	//    5   11:new             #17  <Class IllegalArgumentException>
	//    6   14:dup             
	//    7   15:ldc1            #19  <String "OptionalPendingResult can only wrap PendingResults generated by an API call.">
	//    8   17:invokespecial   #22  <Method void IllegalArgumentException(String)>
	//    9   20:athrow          
		} else
		{
			zzaDb = (zzaaf)pendingresult;
	//   10   21:aload_0         
	//   11   22:aload_1         
	//   12   23:checkcast       #15  <Class zzaaf>
	//   13   26:putfield        #24  <Field zzaaf zzaDb>
			return;
	//   14   29:return          
		}
	}

	public Result await()
	{
		return zzaDb.await();
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:invokevirtual   #31  <Method Result zzaaf.await()>
	//    3    7:areturn         
	}

	public Result await(long l, TimeUnit timeunit)
	{
		return zzaDb.await(l, timeunit);
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:lload_1         
	//    3    5:aload_3         
	//    4    6:invokevirtual   #35  <Method Result zzaaf.await(long, TimeUnit)>
	//    5    9:areturn         
	}

	public void cancel()
	{
		zzaDb.cancel();
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:invokevirtual   #39  <Method void zzaaf.cancel()>
	//    3    7:return          
	}

	public Result get()
	{
		if(isDone())
	//*   0    0:aload_0         
	//*   1    1:invokevirtual   #44  <Method boolean isDone()>
	//*   2    4:ifeq            16
			return await(0L, TimeUnit.MILLISECONDS);
	//    3    7:aload_0         
	//    4    8:lconst_0        
	//    5    9:getstatic       #50  <Field TimeUnit TimeUnit.MILLISECONDS>
	//    6   12:invokevirtual   #51  <Method Result await(long, TimeUnit)>
	//    7   15:areturn         
		else
			throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
	//    8   16:new             #53  <Class IllegalStateException>
	//    9   19:dup             
	//   10   20:ldc1            #55  <String "Result is not available. Check that isDone() returns true before calling get().">
	//   11   22:invokespecial   #56  <Method void IllegalStateException(String)>
	//   12   25:athrow          
	}

	public boolean isCanceled()
	{
		return zzaDb.isCanceled();
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:invokevirtual   #59  <Method boolean zzaaf.isCanceled()>
	//    3    7:ireturn         
	}

	public boolean isDone()
	{
		return zzaDb.isReady();
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:invokevirtual   #62  <Method boolean zzaaf.isReady()>
	//    3    7:ireturn         
	}

	public void setResultCallback(ResultCallback resultcallback)
	{
		zzaDb.setResultCallback(resultcallback);
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:aload_1         
	//    3    5:invokevirtual   #66  <Method void zzaaf.setResultCallback(ResultCallback)>
	//    4    8:return          
	}

	public void setResultCallback(ResultCallback resultcallback, long l, TimeUnit timeunit)
	{
		zzaDb.setResultCallback(resultcallback, l, timeunit);
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:aload_1         
	//    3    5:lload_2         
	//    4    6:aload           4
	//    5    8:invokevirtual   #70  <Method void zzaaf.setResultCallback(ResultCallback, long, TimeUnit)>
	//    6   11:return          
	}

	public TransformedResult then(ResultTransform resulttransform)
	{
		return zzaDb.then(resulttransform);
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:aload_1         
	//    3    5:invokevirtual   #76  <Method TransformedResult zzaaf.then(ResultTransform)>
	//    4    8:areturn         
	}

	public void zza(com.google.android.gms.common.api.PendingResult.zza zza1)
	{
		zzaDb.zza(zza1);
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:aload_1         
	//    3    5:invokevirtual   #83  <Method void zzaaf.zza(com.google.android.gms.common.api.PendingResult$zza)>
	//    4    8:return          
	}

	public Integer zzvr()
	{
		return zzaDb.zzvr();
	//    0    0:aload_0         
	//    1    1:getfield        #24  <Field zzaaf zzaDb>
	//    2    4:invokevirtual   #87  <Method Integer zzaaf.zzvr()>
	//    3    7:areturn         
	}

	private final zzaaf zzaDb;
}
