// Decompiled by Jad v1.5.8g. Copyright 2001 Pavel Kouznetsov.
// Jad home page: http://www.kpdus.com/jad.html
// Decompiler options: packimports(3) annotate safe 

package com.google.android.gms.internal;

import com.google.android.gms.common.api.*;
import com.google.android.gms.common.internal.zzac;
import java.util.concurrent.TimeUnit;

public class zzabp extends PendingResult
{

	public zzabp(Status status)
	{
	//    0    0:aload_0         
	//    1    1:invokespecial   #12  <Method void PendingResult()>
		zzac.zzb(((Object) (status)), "Status must not be null");
	//    2    4:aload_1         
	//    3    5:ldc1            #14  <String "Status must not be null">
	//    4    7:invokestatic    #20  <Method Object zzac.zzb(Object, Object)>
	//    5   10:pop             
		boolean flag;
		if(!status.isSuccess())
	//*   6   11:aload_1         
	//*   7   12:invokevirtual   #26  <Method boolean Status.isSuccess()>
	//*   8   15:ifne            23
			flag = true;
	//    9   18:iconst_1        
	//   10   19:istore_2        
		else
	//*  11   20:goto            25
			flag = false;
	//   12   23:iconst_0        
	//   13   24:istore_2        
		zzac.zzb(flag, "Status must not be success");
	//   14   25:iload_2         
	//   15   26:ldc1            #28  <String "Status must not be success">
	//   16   28:invokestatic    #31  <Method void zzac.zzb(boolean, Object)>
		zzair = status;
	//   17   31:aload_0         
	//   18   32:aload_1         
	//   19   33:putfield        #33  <Field Status zzair>
	//   20   36:return          
	}

	public Result await()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public Result await(long l, TimeUnit timeunit)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void cancel()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	Status getStatus()
	{
		return zzair;
	//    0    0:aload_0         
	//    1    1:getfield        #33  <Field Status zzair>
	//    2    4:areturn         
	}

	public boolean isCanceled()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void setResultCallback(ResultCallback resultcallback)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void setResultCallback(ResultCallback resultcallback, long l, TimeUnit timeunit)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public TransformedResult then(ResultTransform resulttransform)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public void zza(com.google.android.gms.common.api.PendingResult.zza zza1)
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	public Integer zzvr()
	{
		throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
	//    0    0:new             #39  <Class UnsupportedOperationException>
	//    1    3:dup             
	//    2    4:ldc1            #41  <String "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()">
	//    3    6:invokespecial   #44  <Method void UnsupportedOperationException(String)>
	//    4    9:athrow          
	}

	private final Status zzair;
}
